CREATE DATABASE IF NOT EXISTS patient_db_dev;
CREATE DATABASE IF NOT EXISTS patient_db_prod;
CREATE DATABASE IF NOT EXISTS doctor_db_dev;
CREATE DATABASE IF NOT EXISTS doctor_db_prod;
CREATE DATABASE IF NOT EXISTS appointment_db_dev;
CREATE DATABASE IF NOT EXISTS appointment_db_prod;
